version: "3"

networks:
  alex-net:
   driver: bridge
   ipam:
    driver: default
    config:
      - subnet: 172.56.0.0/16

services:

  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - jira-software
#      - confluence
#      - crowd
    networks:
      alex-net:
        ipv4_address: 172.56.1.1

  jira-software:
    restart: unless-stopped
    image: atlassian/jira-software:8.5.2
    container_name: jira-software
    environment:
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=2048m
      - ATL_PROXY_NAME=alex-vm
      - ATL_PROXY_PORT=80
      - ATL_TOMCAT_PORT=8080
      - ATL_TOMCAT_SCHEME=http
      - ATL_TOMCAT_CONTEXTPATH=jira
    volumes:
      - ./jira/data:/var/atlassian/application-data/jira
    depends_on:
      - database
    networks:
      alex-net:
        ipv4_address: 172.56.1.2

#  confluence:
#    image: atlassian/confluence-server:latest
#    volumes:
#      - ./confluence/data:/var/atlassian/application-data/confluence
#    restart: unless-stopped
#    container_name: confluence
#    environment:
#      - JVM_MINIMUM_MEMORY=1024m
#      - JVM_MAXIMUM_MEMORY=2048m
#      - ATL_PROXY_NAME=alex-vm
#      - ATL_PROXY_PORT=80
#      - ATL_TOMCAT_PORT=8090
#      - ATL_TOMCAT_SCHEME=http
#      - ATL_TOMCAT_CONTEXTPATH=confluence
#    depends_on:
#      - jira-software
#    networks:
#      alex-net:
#        ipv4_address: 172.56.1.3
#
#  crowd:
#    image: atlassian/crowd:latest
#    volumes:
#      - ./crowd/data:/var/atlassian/application-data/crowd
#    restart: unless-stopped
#    container_name: crowd
#    environment:
#      - JVM_MINIMUM_MEMORY=512m
#      - JVM_MAXIMUM_MEMORY=1024m
#      - ATL_PROXY_NAME=alex-vm
#      - ATL_PROXY_PORT=80
#      - ATL_TOMCAT_PORT=8095
#      - ATL_TOMCAT_SCHEME=http
#    depends_on:
#      - confluence
#    networks:
#      alex-net:
#        ipv4_address: 172.56.1.4

  database:
      restart: unless-stopped
      image: phoenix795/postgresalexjira:latest
      container_name: postgres
      volumes:
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/backups:/var/lib/postgresql/backups
      networks:
        alex-net:
          ipv4_address: 172.56.1.5


  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - ./prometheus/conf/:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://alex-vm/prometheus'
      - '--web.route-prefix=/'
    expose:
      - 9090
    networks:
      alex-net:
        ipv4_address: 172.56.1.6
    labels:
      org.label-schema.group: "monitoring"


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=alex-vm
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:/grafana
    expose:
      - 3000
    networks:
      alex-net:
        ipv4_address: 172.56.1.7
    labels:
      org.label-schema.group: "monitoring"


  nodeexporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      alex-net:
        ipv4_address: 172.56.1.8
    labels:
      org.label-schema.group: "monitoring"