{
 "title": "Confluence dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "General data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License expires",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_maintenance_expiry_days_gauge"
    }
   ]
  },
  {
   "title": "Global spaces",
   "type": "singlestat",
   "description": "The total global spaces",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "confluence_global_spaces_gauge" }
   ]
  },
  {
   "title": "Personal spaces",
   "type": "singlestat",
   "description": "The total personal spaces",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_personal_spaces_gauge"
    }
   ]
  },
  {
   "title": "Pages",
   "type": "singlestat",
   "description": "The total pages",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "confluence_pages_gauge" }
   ]
  },
  {
   "title": "Active users",
   "type": "singlestat",
   "description": "The active users",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "confluence_active_users_gauge" }
   ]
  },
  {
   "title": "Number of plugins",
   "type": "singlestat",
   "description": "The total plugins",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "confluence_plugin_enabled_count"
    }
   ]
  },
  {
   "title": "Attachments size",
   "type": "singlestat",
   "description": "Displays the current attachments size",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "confluence_total_attachment_size_gauge"
    }
   ]
  },
  {
   "title": "Blog-posts",
   "type": "singlestat",
   "description": "The total blog-posts",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "confluence_blogposts_gauge" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"confluence\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"confluence\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"confluence\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(confluence_request_duration_on_path_sum{job=\"confluence\"}[1m])) by (path)) / (sum(rate(confluence_request_duration_on_path_count{job=\"confluence\"}[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}