{
 "title": "Jira Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Static data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License expires",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "jira_license_expiry_days_gauge" }
   ]
  },
  {
   "title": "Total Projects",
   "type": "singlestat",
   "description": "The total projects in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_projects_gauge" }
   ]
  },
  {
   "title": "Total Issues",
   "type": "singlestat",
   "description": "The total issues in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_issues_gauge" }
   ]
  },
  {
   "title": "Total attachments",
   "type": "singlestat",
   "description": "The total attachments in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_attachments_gauge" }
   ]
  },
  {
   "title": "Total attachments size ",
   "type": "singlestat",
   "description": "The total attachments size in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "jira_total_attachment_size_gauge"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "singlestat",
   "description": "The total users in JIRA",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_all_users_gauge" }
   ]
  },
  {
   "title": "Total Active Users",
   "type": "singlestat",
   "description": "The total active users in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_active_users_gauge" }
   ]
  },
  {
   "title": "Total Custom fields",
   "type": "singlestat",
   "description": "The total customfields in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_customfields_gauge" }
   ]
  },
  {
   "title": "Total Workflows",
   "type": "singlestat",
   "description": "The total workflows in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_workflows_gauge" }
   ]
  },
  {
   "title": "Total Components",
   "type": "singlestat",
   "description": "The total components in JIRA",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jira_total_components_gauge" }
   ]
  },
  { "title": "JVM metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "JVM Memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"jira\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"jira\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"jira\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  { "title": "Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(jira_request_duration_on_path_sum[1m])) by (path)) / (sum(rate(jira_request_duration_on_path_count[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}